services:
  - type: web
    name: cytonn-task-management
    env: docker
    repo: https://github.com/Bryan-cheru/cytonn-task-management.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cytonn-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
    healthCheckPath: /health-simple

databases:
  - name: cytonn-db
    databaseName: task_management
    user: cytonn_user
